### ISSUE TITLE
Isn't Working on Android Devices

### ISSUE THREAD

**Issue by DiMiTriFrog** [nextchapterstudio/walletconnect_qrcode_modal_dart#17]
In Ios its running perfectly, but in Android when I press to Connect on wallet, the  Modal is showing empty with a button "Connect". I can connect wallet scanning the QR, but cant select wallets.

![Screenshot_20221103_171845](https://user-images.githubusercontent.com/38754548/199776101-48de02f7-f20c-4f5d-9128-a3a685fe9806.png)

The Logs when I click the  first button for collect wallet are:
I/flutter ( 8930): State: Connect!
I/flutter ( 8930): State: Connecting

And when I click the new Connect button, the output logs are:
E/flutter ( 8930): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { wc:eaffeaa0-2fe0-4653-b6de-0e2bf8faaff8@1?bridge=https%3A%2F%2Fm.bridge.walletconnect.org&key=082bbfa6e1fd7b38cd2880bb81598a2b4d34a3ab53ac06184904bbf9de52d1e9 }, null, null)
E/flutter ( 8930): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 8930): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter ( 8930): <asynchronous suspension>
E/flutter ( 8930): #2      launchUrl (package:url_launcher/src/url_launcher_uri.dart:53:10)
E/flutter ( 8930): <asynchronous suspension>
E/flutter ( 8930):

**Comment by kevinscheeren** [comment]
The expected behaviour is:

1. on Android instead of having a List it should show the connect button.
2. Pressing the connect button should launch the default "open_in_app" dialog which should show you all apps able to open links
3. from here you can select one of the wallets you have installed
4. connect your wallet with the passed on peer meta
5. the wallet should close and redirect you back to your app

I am using my own package which depends on this, but this shouldn't make a difference. For me this works flawlessly on Android SDK level 33.

<img src="https://user-images.githubusercontent.com/29125263/199802922-8c5047a0-8b4b-4c7a-8435-e7faea48c855.PNG" width="200"><img src="https://user-images.githubusercontent.com/29125263/199802943-557586e0-9909-4b4e-8174-2d11d724a7c3.PNG" width="200"><img src="https://user-images.githubusercontent.com/29125263/199802964-4e2fa99e-b259-4e21-aa17-3f2c67bdb65a.PNG" width="200">

**Comment by 3ph** [comment]
Hi @DiMiTriFrog, as @ilikecubes pointed out this is the expected behavior. We are forced to use the wallet list only because iOS restrictions. The Android way would be normally preferred as you don't have to scroll through the long list but rather select one of your existing wallet apps.

**Comment by DiMiTriFrog** [comment]
Oh, in my Android isnt working share.. It's needed some  share permissions?

**Comment by DiMiTriFrog** [comment]
Right now the button Connect try to open with app, when i select TrustWallet or Metamask, only send  to wallet and nothing is happens..

**Comment by DiMiTriFrog** [comment]
Looks like that only want in 8+ versions of Android

**Comment by 3ph** [comment]
Hi @DiMiTriFrog, so the problem is that when you open the wallet through the Android system dialog nothing happens?

**Comment by DiMiTriFrog** [comment]
> Hi @DiMiTriFrog, so the problem is that when you open the wallet through the Android system dialog nothing happens?

Right, scanning the QR is working always.

**Comment by 3ph** [comment]
@DiMiTriFrog sorry, I somehow completely forgot about this issue. Are you still experiencing it?

**Comment by 3ph** [comment]
Closing as stale
